# This file is part of Unidot Importer. See LICENSE.txt for full MIT license.
# Copyright (c) 2021-present Lyuma <xn.lyuma@gmail.com> and contributors
# SPDX-License-Identifier: MIT
@tool
extends RefCounted

func to_classname(utype: Variant) -> String:
	if typeof(utype) == TYPE_NODE_PATH:
		return str(utype)
	var ret = utype_to_classname.get(utype, "")
	if ret == "":
		return "[UnknownType:" + str(utype) + "]"
	return ret

func to_utype(classname: String) -> int:
	return classname_to_utype.get(classname, 0)

func instantiate_unidot_object(meta: Object, fileID: int, utype: int, type: String) -> UnidotObject:
	var ret: UnidotObject = null
	var actual_type: String = type
	if utype != 0 and utype_to_classname.has(utype):
		actual_type = utype_to_classname[utype]
		if actual_type != type and (type != "Behaviour" or actual_type != "FlareLayer") and (type != "Prefab" or actual_type != "PrefabInstance"):
			meta.log_warn(fileID, "Mismatched type:" + type + " vs. utype:" + str(utype) + ":" + actual_type)
	if _type_dictionary.has(actual_type):
		# meta.log_debug(fileID, "Will instantiate object of type " + str(actual_type) + "/" + str(type) + "/" + str(utype) + "/" + str(classname_to_utype.get(actual_type, utype)))
		ret = _type_dictionary[actual_type].new()
	else:
		meta.log_fail(fileID, "Failed to instantiate object of type " + str(actual_type) + "/" + str(type) + "/" + str(utype) + "/" + str(classname_to_utype.get(actual_type, utype)))
		if type.ends_with("Importer"):
			ret = UnidotAssetImporter.new()
		else:
			ret = UnidotObject.new()
	ret.meta = meta
	ret.adapter = self
	ret.fileID = fileID
	if utype != 0 and utype != classname_to_utype.get(actual_type, utype):
		meta.log_warn(fileID, "Mismatched utype " + str(utype) + " for " + type)
	ret.utype = classname_to_utype.get(actual_type, utype)
	ret.type = actual_type
	return ret


func instantiate_unidot_object_from_utype(meta: Object, fileID: int, utype: int) -> UnidotObject:
	var ret: UnidotObject = null
	if not utype_to_classname.has(utype):
		meta.log_fail(fileID, "Unknown utype " + str(utype))
		return
	var actual_type: String = utype_to_classname[utype]
	if _type_dictionary.has(actual_type):
		ret = _type_dictionary[actual_type].new()
	else:
		meta.log_fail(fileID, "Failed to instantiate object of type " + str(actual_type) + "/" + str(utype) + "/" + str(classname_to_utype.get(actual_type, utype)))
		ret = UnidotObject.new()
	ret.meta = meta
	ret.adapter = self
	ret.fileID = fileID
	ret.utype = classname_to_utype.get(actual_type, utype)
	ret.type = actual_type
	return ret

func invert_hashtable(ht: Dictionary) -> Dictionary:
	var outd: Dictionary = Dictionary()
	for key in ht:
		outd[ht[key]] = key
	return outd

var _type_dictionary: Dictionary = {
	# "AimConstraint": UnidotAimConstraint,
	# "AnchoredJoint2D": UnidotAnchoredJoint2D,
	"Animation": UnidotAnimation,
	"AnimationClip": UnidotAnimationClip,
	"Animator": UnidotAnimator,
	"AnimatorController": UnidotAnimatorController,
	"AnimatorOverrideController": UnidotAnimatorOverrideController,
	"AnimatorState": UnidotAnimatorState,
	"AnimatorStateMachine": UnidotAnimatorStateMachine,
	"AnimatorStateTransition": UnidotAnimatorStateTransition,
	"AnimatorTransition": UnidotAnimatorTransition,
	"AnimatorTransitionBase": UnidotAnimatorTransitionBase,
	# "AnnotationManager": UnidotAnnotationManager,
	# "AreaEffector2D": UnidotAreaEffector2D,
	# "AssemblyDefinitionAsset": UnidotAssemblyDefinitionAsset,
	# "AssemblyDefinitionImporter": UnidotAssemblyDefinitionImporter,
	# "AssemblyDefinitionReferenceAsset": UnidotAssemblyDefinitionReferenceAsset,
	# "AssemblyDefinitionReferenceImporter": UnidotAssemblyDefinitionReferenceImporter,
	# "AssetBundle": UnidotAssetBundle,
	# "AssetBundleManifest": UnidotAssetBundleManifest,
	# "AssetDatabaseV1": UnidotAssetDatabaseV1,
	"AssetImporter": UnidotAssetImporter,
	# "AssetImporterLog": UnidotAssetImporterLog,
	# "AssetImportInProgressProxy": UnidotAssetImportInProgressProxy,
	# "AssetMetaData": UnidotAssetMetaData,
	# "AudioBehaviour": UnidotAudioBehaviour,
	# "AudioBuildInfo": UnidotAudioBuildInfo,
	# "AudioChorusFilter": UnidotAudioChorusFilter,
	"AudioClip": UnidotAudioClip,
	# "AudioDistortionFilter": UnidotAudioDistortionFilter,
	# "AudioEchoFilter": UnidotAudioEchoFilter,
	# "AudioFilter": UnidotAudioFilter,
	# "AudioHighPassFilter": UnidotAudioHighPassFilter,
	"AudioImporter": UnidotAudioImporter,
	"AudioListener": DiscardUnidotComponent,
	# "AudioLowPassFilter": UnidotAudioLowPassFilter,
	# "AudioManager": UnidotAudioManager,
	# "AudioMixer": UnidotAudioMixer,
	# "AudioMixerController": UnidotAudioMixerController,
	# "AudioMixerEffectController": UnidotAudioMixerEffectController,
	# "AudioMixerGroup": UnidotAudioMixerGroup,
	# "AudioMixerGroupController": UnidotAudioMixerGroupController,
	# "AudioMixerLiveUpdateBool": UnidotAudioMixerLiveUpdateBool,
	# "AudioMixerLiveUpdateFloat": UnidotAudioMixerLiveUpdateFloat,
	# "AudioMixerSnapshot": UnidotAudioMixerSnapshot,
	# "AudioMixerSnapshotController": UnidotAudioMixerSnapshotController,
	# "AudioReverbFilter": UnidotAudioReverbFilter,
	# "AudioReverbZone": UnidotAudioReverbZone,
	"AudioSource": UnidotAudioSource,
	"Avatar": UnidotAvatar,
	"AvatarMask": UnidotAvatarMask,
	# "BaseAnimationTrack": UnidotBaseAnimationTrack,
	# "BaseVideoTexture": UnidotBaseVideoTexture,
	"Behaviour": UnidotBehaviour,
	# "BillboardAsset": UnidotBillboardAsset,
	# "BillboardRenderer": UnidotBillboardRenderer,
	"BlendTree": UnidotBlendTree,
	"BoxCollider": UnidotBoxCollider,
	# "BoxCollider2D": UnidotBoxCollider2D,
	# "BuildReport": UnidotBuildReport,
	# "BuildSettings": UnidotBuildSettings,
	# "BuiltAssetBundleInfoSet": UnidotBuiltAssetBundleInfoSet,
	# "BuoyancyEffector2D": UnidotBuoyancyEffector2D,
	# "CachedSpriteAtlas": UnidotCachedSpriteAtlas,
	# "CachedSpriteAtlasRuntimeData": UnidotCachedSpriteAtlasRuntimeData,
	"Camera": UnidotCamera,
	# "Canvas": UnidotCanvas,
	# "CanvasGroup": UnidotCanvasGroup,
	# "CanvasRenderer": UnidotCanvasRenderer,
	"CapsuleCollider": UnidotCapsuleCollider,
	# "CapsuleCollider2D": UnidotCapsuleCollider2D,
	# "CGProgram": UnidotCGProgram,
	"CharacterController": UnidotCharacterController,
	# "CharacterJoint": UnidotCharacterJoint,
	# "CircleCollider2D": UnidotCircleCollider2D,
	"Cloth": UnidotCloth,
	# "ClusterInputManager": UnidotClusterInputManager,
	"Collider": UnidotCollider,
	# "Collider2D": UnidotCollider2D,
	# "Collision": UnidotCollision,
	# "Collision2D": UnidotCollision2D,
	"Component": UnidotComponent,
	# "CompositeCollider2D": UnidotCompositeCollider2D,
	# "ComputeShader": UnidotComputeShader,
	# "ComputeShaderImporter": UnidotComputeShaderImporter,
	# "ConfigurableJoint": UnidotConfigurableJoint,
	# "ConstantForce": UnidotConstantForce,
	# "ConstantForce2D": UnidotConstantForce2D,
	"Cubemap": UnidotCubemap,
	"CubemapArray": UnidotCubemapArray,
	"CustomRenderTexture": UnidotCustomRenderTexture,
	# "DefaultAsset": UnidotDefaultAsset,
	"DefaultImporter": UnidotDefaultImporter,
	# "DelayedCallManager": UnidotDelayedCallManager,
	# "Derived": UnidotDerived,
	# "DistanceJoint2D": UnidotDistanceJoint2D,
	# "EdgeCollider2D": UnidotEdgeCollider2D,
	# "EditorBuildSettings": UnidotEditorBuildSettings,
	# "EditorExtension": UnidotEditorExtension,
	# "EditorExtensionImpl": UnidotEditorExtensionImpl,
	# "EditorProjectAccess": UnidotEditorProjectAccess,
	# "EditorSettings": UnidotEditorSettings,
	# "EditorUserBuildSettings": UnidotEditorUserBuildSettings,
	# "EditorUserSettings": UnidotEditorUserSettings,
	# "Effector2D": UnidotEffector2D,
	# "EmptyObject": UnidotEmptyObject,
	# "FakeComponent": UnidotFakeComponent,
	# "FBXImporter": UnidotFBXImporter,
	# "FixedJoint": UnidotFixedJoint,
	# "FixedJoint2D": UnidotFixedJoint2D,
	# "Flare": UnidotFlare,
	"FlareLayer": DiscardUnidotComponent,
	# "float": Unidotfloat,
	# "Font": UnidotFont,
	# "FrictionJoint2D": UnidotFrictionJoint2D,
	# "GameManager": UnidotGameManager,
	"GameObject": UnidotGameObject,
	# "GameObjectRecorder": UnidotGameObjectRecorder,
	# "GlobalGameManager": UnidotGlobalGameManager,
	# "GraphicsSettings": UnidotGraphicsSettings,
	# "Grid": UnidotGrid,
	# "GridLayout": UnidotGridLayout,
	# "Halo": UnidotHalo,
	"HaloLayer": DiscardUnidotComponent,
	# "HierarchyState": UnidotHierarchyState,
	# "HingeJoint": UnidotHingeJoint,
	# "HingeJoint2D": UnidotHingeJoint2D,
	# "HumanTemplate": UnidotHumanTemplate,
	# "IConstraint": UnidotIConstraint,
	# "IHVImageFormatImporter": UnidotIHVImageFormatImporter,
	# "InputManager": UnidotInputManager,
	# "InspectorExpandedState": UnidotInspectorExpandedState,
	# "Joint": UnidotJoint,
	# "Joint2D": UnidotJoint2D,
	# "LensFlare": UnidotLensFlare,
	# "LevelGameManager": UnidotLevelGameManager,
	# "LibraryAssetImporter": UnidotLibraryAssetImporter,
	"Light": UnidotLight,
	# "LightingDataAsset": UnidotLightingDataAsset,
	# "LightingDataAssetParent": UnidotLightingDataAssetParent,
	# "LightmapParameters": UnidotLightmapParameters,
	"LightmapSettings": DiscardUnidotComponent,
	"LightProbeGroup": UnidotLightProbeGroup,
	# "LightProbeProxyVolume": UnidotLightProbeProxyVolume,
	# "LightProbes": UnidotLightProbes,
	# "LineRenderer": UnidotLineRenderer,
	# "LocalizationAsset": UnidotLocalizationAsset,
	# "LocalizationImporter": UnidotLocalizationImporter,
	"LODGroup": UnidotLODGroup,
	# "LookAtConstraint": UnidotLookAtConstraint,
	# "LowerResBlitTexture": UnidotLowerResBlitTexture,
	"Material": UnidotMaterial,
	"Mesh": UnidotMesh,
	# "Mesh3DSImporter": UnidotMesh3DSImporter,
	"MeshCollider": UnidotMeshCollider,
	"MeshFilter": UnidotMeshFilter,
	"MeshRenderer": UnidotMeshRenderer,
	"ModelImporter": UnidotModelImporter,
	"MonoBehaviour": UnidotMonoBehaviour,
	# "MonoImporter": UnidotMonoImporter,
	# "MonoManager": UnidotMonoManager,
	# "MonoObject": UnidotMonoObject,
	# "MonoScript": UnidotMonoScript,
	"Motion": UnidotMotion,
	# "NamedObject": UnidotNamedObject,
	"NativeFormatImporter": UnidotNativeFormatImporter,
	# "NativeObjectType": UnidotNativeObjectType,
	# "NavMeshAgent": UnidotNavMeshAgent,
	# "NavMeshData": UnidotNavMeshData,
	# "NavMeshObstacle": UnidotNavMeshObstacle,
	# "NavMeshProjectSettings": UnidotNavMeshProjectSettings,
	"NavMeshSettings": DiscardUnidotComponent,
	# "NewAnimationTrack": UnidotNewAnimationTrack,
	"Object": UnidotObject,
	# "OcclusionArea": UnidotOcclusionArea,
	# "OcclusionCullingData": UnidotOcclusionCullingData,
	"OcclusionCullingSettings": DiscardUnidotComponent,
	# "OcclusionPortal": UnidotOcclusionPortal,
	# "OffMeshLink": UnidotOffMeshLink,
	# "PackageManifest": UnidotPackageManifest,
	# "PackageManifestImporter": UnidotPackageManifestImporter,
	# "PackedAssets": UnidotPackedAssets,
	# "ParentConstraint": UnidotParentConstraint,
	# "ParticleSystem": UnidotParticleSystem,
	# "ParticleSystemForceField": UnidotParticleSystemForceField,
	# "ParticleSystemRenderer": UnidotParticleSystemRenderer,
	"PhysicMaterial": UnidotPhysicMaterial,
	# "Physics2DSettings": UnidotPhysics2DSettings,
	# "PhysicsManager": UnidotPhysicsManager,
	# "PhysicsMaterial2D": UnidotPhysicsMaterial2D,
	# "PhysicsUpdateBehaviour2D": UnidotPhysicsUpdateBehaviour2D,
	# "PlatformEffector2D": UnidotPlatformEffector2D,
	# "PlatformModuleSetup": UnidotPlatformModuleSetup,
	# "PlayableDirector": UnidotPlayableDirector,
	# "PlayerSettings": UnidotPlayerSettings,
	# "PluginBuildInfo": UnidotPluginBuildInfo,
	# "PluginImporter": UnidotPluginImporter,
	# "PointEffector2D": UnidotPointEffector2D,
	# "Polygon2D": UnidotPolygon2D,
	# "PolygonCollider2D": UnidotPolygonCollider2D,
	# "PositionConstraint": UnidotPositionConstraint,
	"Prefab": UnidotPrefabLegacyUnused,
	"PrefabImporter": UnidotPrefabImporter,
	"PrefabInstance": UnidotPrefabInstance,
	# "PreloadData": UnidotPreloadData,
	# "Preset": UnidotPreset,
	# "PresetManager": UnidotPresetManager,
	# "Projector": UnidotProjector,
	# "QualitySettings": UnidotQualitySettings,
	# "RayTracingShader": UnidotRayTracingShader,
	# "RayTracingShaderImporter": UnidotRayTracingShaderImporter,
	"RectTransform": UnidotRectTransform,
	# "ReferencesArtifactGenerator": UnidotReferencesArtifactGenerator,
	"ReflectionProbe": UnidotReflectionProbe,
	# "RelativeJoint2D": UnidotRelativeJoint2D,
	"Renderer": UnidotRenderer,
	# "RendererFake": UnidotRendererFake,
	"RenderSettings": DiscardUnidotComponent,
	"RenderTexture": UnidotRenderTexture,
	# "ResourceManager": UnidotResourceManager,
	"Rigidbody": UnidotRigidbody,
	# "Rigidbody2D": UnidotRigidbody2D,
	# "RootMotionData": UnidotRootMotionData,
	# "RotationConstraint": UnidotRotationConstraint,
	"RuntimeAnimatorController": UnidotRuntimeAnimatorController,
	# "RuntimeInitializeOnLoadManager": UnidotRuntimeInitializeOnLoadManager,
	# "SampleClip": UnidotSampleClip,
	# "ScaleConstraint": UnidotScaleConstraint,
	# "SceneAsset": UnidotSceneAsset,
	# "SceneVisibilityState": UnidotSceneVisibilityState,
	# "ScriptedImporter": UnidotScriptedImporter,
	# "ScriptMapper": UnidotScriptMapper,
	# "SerializableManagedHost": UnidotSerializableManagedHost,
	# "Shader": UnidotShader,
	"ShaderImporter": UnidotShaderImporter,
	# "ShaderVariantCollection": UnidotShaderVariantCollection,
	# "SiblingDerived": UnidotSiblingDerived,
	# "SketchUpImporter": UnidotSketchUpImporter,
	"SkinnedMeshRenderer": UnidotSkinnedMeshRenderer,
	# "Skybox": UnidotSkybox,
	# "SliderJoint2D": UnidotSliderJoint2D,
	# "SortingGroup": UnidotSortingGroup,
	# "SparseTexture": UnidotSparseTexture,
	# "SpeedTreeImporter": UnidotSpeedTreeImporter,
	# "SpeedTreeWindAsset": UnidotSpeedTreeWindAsset,
	"SphereCollider": UnidotSphereCollider,
	# "SpringJoint": UnidotSpringJoint,
	# "SpringJoint2D": UnidotSpringJoint2D,
	# "Sprite": UnidotSprite,
	# "SpriteAtlas": UnidotSpriteAtlas,
	# "SpriteAtlasDatabase": UnidotSpriteAtlasDatabase,
	# "SpriteMask": UnidotSpriteMask,
	# "SpriteRenderer": UnidotSpriteRenderer,
	# "SpriteShapeRenderer": UnidotSpriteShapeRenderer,
	# "StreamingController": UnidotStreamingController,
	# "StreamingManager": UnidotStreamingManager,
	# "SubDerived": UnidotSubDerived,
	# "SubstanceArchive": UnidotSubstanceArchive,
	# "SubstanceImporter": UnidotSubstanceImporter,
	# "SurfaceEffector2D": UnidotSurfaceEffector2D,
	# "TagManager": UnidotTagManager,
	# "TargetJoint2D": UnidotTargetJoint2D,
	"Terrain": UnidotTerrain,
	"TerrainCollider": UnidotTerrainCollider,
	"TerrainData": UnidotTerrainData,
	"TerrainLayer": UnidotTerrainLayer,
	"TextAsset": UnidotTextAsset,
	"TextMesh": UnidotTextMesh,
	"TextScriptImporter": UnidotTextScriptImporter,
	"Texture": UnidotTexture,
	"Texture2D": UnidotTexture2D,
	"Texture2DArray": UnidotTexture2DArray,
	"Texture3D": UnidotTexture3D,
	"TextureImporter": UnidotTextureImporter,
	# "Tilemap": UnidotTilemap,
	# "TilemapCollider2D": UnidotTilemapCollider2D,
	# "TilemapRenderer": UnidotTilemapRenderer,
	# "TimeManager": UnidotTimeManager,
	# "TrailRenderer": UnidotTrailRenderer,
	"Transform": UnidotTransform,
	# "Tree": UnidotTree,
	"TrueTypeFontImporter": UnidotTrueTypeFontImporter,
	# "UnidotConnectSettings": UnidotUnidotConnectSettings,
	# "Vector3f": UnidotVector3f,
	# "VFXManager": UnidotVFXManager,
	# "VFXRenderer": UnidotVFXRenderer,
	# "VideoClip": UnidotVideoClip,
	# "VideoClipImporter": UnidotVideoClipImporter,
	# "VideoPlayer": UnidotVideoPlayer,
	# "VisualEffect": UnidotVisualEffect,
	# "VisualEffectAsset": UnidotVisualEffectAsset,
	# "VisualEffectImporter": UnidotVisualEffectImporter,
	# "VisualEffectObject": UnidotVisualEffectObject,
	# "VisualEffectResource": UnidotVisualEffectResource,
	# "VisualEffectSubgraph": UnidotVisualEffectSubgraph,
	# "VisualEffectSubgraphBlock": UnidotVisualEffectSubgraphBlock,
	# "VisualEffectSubgraphOperator": UnidotVisualEffectSubgraphOperator,
	# "WebCamTexture": UnidotWebCamTexture,
	# "WheelCollider": UnidotWheelCollider,
	# "WheelJoint2D": UnidotWheelJoint2D,
	# "WindZone": UnidotWindZone,
	# "WorldAnchor": UnidotWorldAnchor,
}

var utype_to_classname = {
	0: "Object",
	1: "GameObject",
	2: "Component",
	3: "LevelGameManager",
	4: "Transform",
	5: "TimeManager",
	6: "GlobalGameManager",
	8: "Behaviour",
	9: "GameManager",
	11: "AudioManager",
	13: "InputManager",
	18: "EditorExtension",
	19: "Physics2DSettings",
	20: "Camera",
	21: "Material",
	23: "MeshRenderer",
	25: "Renderer",
	27: "Texture",
	28: "Texture2D",
	29: "OcclusionCullingSettings",
	30: "GraphicsSettings",
	33: "MeshFilter",
	41: "OcclusionPortal",
	43: "Mesh",
	45: "Skybox",
	47: "QualitySettings",
	48: "Shader",
	49: "TextAsset",
	50: "Rigidbody2D",
	53: "Collider2D",
	54: "Rigidbody",
	55: "PhysicsManager",
	56: "Collider",
	57: "Joint",
	58: "CircleCollider2D",
	59: "HingeJoint",
	60: "PolygonCollider2D",
	61: "BoxCollider2D",
	62: "PhysicsMaterial2D",
	64: "MeshCollider",
	65: "BoxCollider",
	66: "CompositeCollider2D",
	68: "EdgeCollider2D",
	70: "CapsuleCollider2D",
	72: "ComputeShader",
	74: "AnimationClip",
	75: "ConstantForce",
	78: "TagManager",
	81: "AudioListener",
	82: "AudioSource",
	83: "AudioClip",
	84: "RenderTexture",
	86: "CustomRenderTexture",
	89: "Cubemap",
	90: "Avatar",
	91: "AnimatorController",
	93: "RuntimeAnimatorController",
	94: "ScriptMapper",
	95: "Animator",
	96: "TrailRenderer",
	98: "DelayedCallManager",
	102: "TextMesh",
	104: "RenderSettings",
	108: "Light",
	109: "CGProgram",
	110: "BaseAnimationTrack",
	111: "Animation",
	114: "MonoBehaviour",
	115: "MonoScript",
	116: "MonoManager",
	117: "Texture3D",
	118: "NewAnimationTrack",
	119: "Projector",
	120: "LineRenderer",
	121: "Flare",
	122: "Halo",
	123: "LensFlare",
	124: "FlareLayer",
	125: "HaloLayer",
	126: "NavMeshProjectSettings",
	128: "Font",
	129: "PlayerSettings",
	130: "NamedObject",
	134: "PhysicMaterial",
	135: "SphereCollider",
	136: "CapsuleCollider",
	137: "SkinnedMeshRenderer",
	138: "FixedJoint",
	141: "BuildSettings",
	142: "AssetBundle",
	143: "CharacterController",
	144: "CharacterJoint",
	145: "SpringJoint",
	146: "WheelCollider",
	147: "ResourceManager",
	150: "PreloadData",
	153: "ConfigurableJoint",
	154: "TerrainCollider",
	156: "TerrainData",
	157: "LightmapSettings",
	158: "WebCamTexture",
	159: "EditorSettings",
	162: "EditorUserSettings",
	164: "AudioReverbFilter",
	165: "AudioHighPassFilter",
	166: "AudioChorusFilter",
	167: "AudioReverbZone",
	168: "AudioEchoFilter",
	169: "AudioLowPassFilter",
	170: "AudioDistortionFilter",
	171: "SparseTexture",
	180: "AudioBehaviour",
	181: "AudioFilter",
	182: "WindZone",
	183: "Cloth",
	184: "SubstanceArchive",
	185: "ProceduralMaterial",
	186: "ProceduralTexture",
	187: "Texture2DArray",
	188: "CubemapArray",
	191: "OffMeshLink",
	192: "OcclusionArea",
	193: "Tree",
	195: "NavMeshAgent",
	196: "NavMeshSettings",
	198: "ParticleSystem",
	199: "ParticleSystemRenderer",
	200: "ShaderVariantCollection",
	205: "LODGroup",
	206: "BlendTree",
	207: "Motion",
	208: "NavMeshObstacle",
	210: "SortingGroup",
	212: "SpriteRenderer",
	213: "Sprite",
	214: "CachedSpriteAtlas",
	215: "ReflectionProbe",
	218: "Terrain",
	220: "LightProbeGroup",
	221: "AnimatorOverrideController",
	222: "CanvasRenderer",
	223: "Canvas",
	224: "RectTransform",
	225: "CanvasGroup",
	226: "BillboardAsset",
	227: "BillboardRenderer",
	228: "SpeedTreeWindAsset",
	229: "AnchoredJoint2D",
	230: "Joint2D",
	231: "SpringJoint2D",
	232: "DistanceJoint2D",
	233: "HingeJoint2D",
	234: "SliderJoint2D",
	235: "WheelJoint2D",
	236: "ClusterInputManager",
	237: "BaseVideoTexture",
	238: "NavMeshData",
	240: "AudioMixer",
	241: "AudioMixerController",
	243: "AudioMixerGroupController",
	244: "AudioMixerEffectController",
	245: "AudioMixerSnapshotController",
	246: "PhysicsUpdateBehaviour2D",
	247: "ConstantForce2D",
	248: "Effector2D",
	249: "AreaEffector2D",
	250: "PointEffector2D",
	251: "PlatformEffector2D",
	252: "SurfaceEffector2D",
	253: "BuoyancyEffector2D",
	254: "RelativeJoint2D",
	255: "FixedJoint2D",
	256: "FrictionJoint2D",
	257: "TargetJoint2D",
	258: "LightProbes",
	259: "LightProbeProxyVolume",
	271: "SampleClip",
	272: "AudioMixerSnapshot",
	273: "AudioMixerGroup",
	290: "AssetBundleManifest",
	300: "RuntimeInitializeOnLoadManager",
	310: "UnidotConnectSettings",
	319: "AvatarMask",
	320: "PlayableDirector",
	328: "VideoPlayer",
	329: "VideoClip",
	330: "ParticleSystemForceField",
	331: "SpriteMask",
	362: "WorldAnchor",
	363: "OcclusionCullingData",
	1001: "PrefabInstance",
	1002: "EditorExtensionImpl",
	1003: "AssetImporter",
	1004: "AssetDatabaseV1",
	1005: "Mesh3DSImporter",
	1006: "TextureImporter",
	1007: "ShaderImporter",
	1008: "ComputeShaderImporter",
	1020: "AudioImporter",
	1026: "HierarchyState",
	1028: "AssetMetaData",
	1029: "DefaultAsset",
	1030: "DefaultImporter",
	1031: "TextScriptImporter",
	1032: "SceneAsset",
	1034: "NativeFormatImporter",
	1035: "MonoImporter",
	1038: "LibraryAssetImporter",
	1040: "ModelImporter",
	1041: "FBXImporter",
	1042: "TrueTypeFontImporter",
	1045: "EditorBuildSettings",
	1048: "InspectorExpandedState",
	1049: "AnnotationManager",
	1050: "PluginImporter",
	1051: "EditorUserBuildSettings",
	1055: "IHVImageFormatImporter",
	1101: "AnimatorStateTransition",
	1102: "AnimatorState",
	1105: "HumanTemplate",
	1107: "AnimatorStateMachine",
	1108: "PreviewAnimationClip",
	1109: "AnimatorTransition",
	1110: "SpeedTreeImporter",
	1111: "AnimatorTransitionBase",
	1112: "SubstanceImporter",
	1113: "LightmapParameters",
	1120: "LightingDataAsset",
	1124: "SketchUpImporter",
	1125: "BuildReport",
	1126: "PackedAssets",
	1127: "VideoClipImporter",
	100000: "int",
	100001: "bool",
	100002: "float",
	100003: "MonoObject",
	100004: "Collision",
	100005: "Vector3f",
	100006: "RootMotionData",
	100007: "Collision2D",
	100008: "AudioMixerLiveUpdateFloat",
	100009: "AudioMixerLiveUpdateBool",
	100010: "Polygon2D",
	100011: "void",
	19719996: "TilemapCollider2D",
	41386430: "AssetImporterLog",
	73398921: "VFXRenderer",
	156049354: "Grid",
	181963792: "Preset",
	277625683: "EmptyObject",
	285090594: "IConstraint",
	294290339: "AssemblyDefinitionReferenceImporter",
	334799969: "SiblingDerived",
	367388927: "SubDerived",
	369655926: "AssetImportInProgressProxy",
	382020655: "PluginBuildInfo",
	426301858: "EditorProjectAccess",
	468431735: "PrefabImporter",
	483693784: "TilemapRenderer",
	638013454: "SpriteAtlasDatabase",
	641289076: "AudioBuildInfo",
	644342135: "CachedSpriteAtlasRuntimeData",
	646504946: "RendererFake",
	662584278: "AssemblyDefinitionReferenceAsset",
	668709126: "BuiltAssetBundleInfoSet",
	687078895: "SpriteAtlas",
	747330370: "RayTracingShaderImporter",
	825902497: "RayTracingShader",
	877146078: "PlatformModuleSetup",
	895512359: "AimConstraint",
	937362698: "VFXManager",
	994735392: "VisualEffectSubgraph",
	994735403: "VisualEffectSubgraphOperator",
	994735404: "VisualEffectSubgraphBlock",
	1001480554: "Prefab",
	1027052791: "LocalizationImporter",
	1091556383: "Derived",
	1114811875: "ReferencesArtifactGenerator",
	1152215463: "AssemblyDefinitionAsset",
	1154873562: "SceneVisibilityState",
	1183024399: "LookAtConstraint",
	1268269756: "GameObjectRecorder",
	1325145578: "LightingDataAssetParent",
	1386491679: "PresetManager",
	1403656975: "StreamingManager",
	1480428607: "LowerResBlitTexture",
	1542919678: "StreamingController",
	1742807556: "GridLayout",
	1766753193: "AssemblyDefinitionImporter",
	1773428102: "ParentConstraint",
	1803986026: "FakeComponent",
	1818360608: "PositionConstraint",
	1818360609: "RotationConstraint",
	1818360610: "ScaleConstraint",
	1839735485: "Tilemap",
	1896753125: "PackageManifest",
	1896753126: "PackageManifestImporter",
	1953259897: "TerrainLayer",
	1971053207: "SpriteShapeRenderer",
	1977754360: "NativeObjectType",
	1995898324: "SerializableManagedHost",
	2058629509: "VisualEffectAsset",
	2058629510: "VisualEffectImporter",
	2058629511: "VisualEffectResource",
	2059678085: "VisualEffectObject",
	2083052967: "VisualEffect",
	2083778819: "LocalizationAsset",
	208985858483: "ScriptedImporter",
}

var classname_to_utype: Dictionary = invert_hashtable(utype_to_classname)
